In [1]:
import numpy as np
import pandas as pd

from pathlib import Path
from pycaret.classification import setup, compare_models

In [2]:
DATA_DIR = Path.cwd().resolve().parent / "data"

df_data = pd.read_parquet(DATA_DIR / "02_data_ataques_cardiacos_transformados.parquet")

# Seleccion de columnas

In [3]:
df_data.columns

Index(['age', 'gender', 'heart_rate', 'systolic_bp', 'diastolic_bp',
       'blood_sugar', 'ckmb', 'troponin', 'result'],
      dtype='object')

In [4]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           1319 non-null   float64
 1   gender        1319 non-null   int64
 2   heart_rate    1319 non-null   float64
 3   systolic_bp   1319 non-null   float64
 4   diastolic_bp  1319 non-null   float64
 5   blood_sugar   1319 non-null   float64
 6   ckmb          1319 non-null   float64
 7   troponin      1319 non-null   float64
 8   result        1319 non-null   bool
dtypes: bool(1), float64(7), int64(1)
memory usage: 83.9 KB

In [5]:
target_col = 'result'

In [6]:
#Creacion del setup
models_setup = setup(
    data = df_data,
    target = target_col,
    session_id = 42,

    #Parametros para el pre-procesamiento
    numeric_features = ['age','heart_rate','systolic_bp','diastolic_bp','blood_sugar','ckmb','troponin'],
    categorical_features = ['gender'],

    #estrategias de imputacion
    numeric_imputation= 'mean',
    categorical_imputation = 'mode',
)

In [7]:
df_data['result'].value_counts()

result
True     810
False    509
Name: count, dtype: int64

In [8]:
best_model = compare_models(
    include = ['lr','rf','gbc','lightgbm','knn','xgboost'],
    sort = 'Accuracy',
    n_select = 3
)

In [9]:
from pycaret.classification import create_model, tune_model, predict_model

print("Creando el modelo Random Forest Classifier...")
gbc_model = create_model('rf')

print("\n")
print("------")
print("\n")

print("Realizando fine-tuning del modelo....")
gbc_tuned = tune_model(gbc_model)

print("\n")
print("------")
print("\n")

print("Resumen del modelo")
print(gbc_tuned)

print("\n")
print("------")
print("\n")

print("Predicciones en el conjunto/set de test")
internal_predictions = predict_model(gbc_tuned)

print("\n")
print("------")
print("\n")


print(internal_predictions.head())

Creando el modelo Random Forest Classifier...

Initiated  . . . . . . . . . . . . . . . . . .                  23:10:32
Status     . . . . . . . . . . . . . . . . . .          Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Random Forest Classifier

------


Realizando fine-tuning del modelo....

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


------


Resumen del modelo
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=42, verbose=0,
                       warm_start=False)


------


Predicciones en el conjunto/set de test

------


       age  gender  heart_rate  systolic_bp  diastolic_bp  blood_sugar  \
158   68.0       1        61.0        122.0          66.0         95.0
1174  37.0       0        83.0        102.0          68.0        104.0
78    50.0       1        64.0        110.0          58.0         90.0
346   60.0       1       134.0        111.0          69.0        163.0
699   65.0       1        87.0        115.0          78.0        119.0

        ckmb  troponin  result  prediction_label  prediction_score
158    3.450     0.013   False                 0              0.89
1174   1.350     0.007   False                 0              0.96
78     0.994     0.864    True                 1              0.98
346    3.080     0.025    True                 1              0.96
699   17.320     1.390    True                 1              0.99

In [10]:
print(gbc_tuned.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

In [11]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           1319 non-null   float64
 1   gender        1319 non-null   int64
 2   heart_rate    1319 non-null   float64
 3   systolic_bp   1319 non-null   float64
 4   diastolic_bp  1319 non-null   float64
 5   blood_sugar   1319 non-null   float64
 6   ckmb          1319 non-null   float64
 7   troponin      1319 non-null   float64
 8   result        1319 non-null   bool
dtypes: bool(1), float64(7), int64(1)
memory usage: 83.9 KB

In [12]:
np.random.seed(57)

n_samples = 50

df_data_test = pd.DataFrame({
    'age':np.random.uniform(14,103, size=n_samples),
    'gender':np.random.choice([0,1], size=n_samples),
    'heart_rate':np.random.uniform(20,1111, size=n_samples),
    'systolic_bp':np.random.uniform(42,223, size=n_samples),
    'diastolic_bp':np.random.uniform(38,154, size=n_samples),
    'blood_sugar':np.random.uniform(35,541, size=n_samples),
    'ckmb':np.random.uniform(0.3,300, size=n_samples),
    'troponin':np.random.uniform(0.00,10.3, size=n_samples)
})

df_data_test.head()

,age,gender,heart_rate,systolic_bp,diastolic_bp,blood_sugar,ckmb,troponin
0,21.774118,1,742.241148,51.203774,102.508589,247.243620,138.185377,4.275240
1,34.512462,0,651.352424,139.388856,123.839720,451.762404,205.272710,0.474470
2,50.584435,1,358.905925,55.958721,133.746619,460.656746,27.015308,2.549984
3,41.659660,1,446.811779,112.579640,72.924634,283.157767,0.743010,4.637761
4,64.370074,1,470.737845,184.010908,51.851122,451.823847,190.036728,3.515082

In [13]:
synthetic_predictions = predict_model(gbc_model, data=df_data_test)

synthetic_predictions.head()

,age,gender,heart_rate,systolic_bp,diastolic_bp,blood_sugar,ckmb,troponin,prediction_label,prediction_score
0,21.774118,1,742.241150,51.203773,102.508591,247.243622,138.185379,4.275239,1,0.88
1,34.512463,0,651.352417,139.388855,123.839722,451.762390,205.272705,0.474470,1,0.96
2,50.584435,1,358.905914,55.958721,133.746613,460.656738,27.015308,2.549984,1,0.96
3,41.659660,1,446.811768,112.579643,72.924637,283.157776,0.743010,4.637761,1,0.92
4,64.370071,1,470.737854,184.010910,51.851124,451.823853,190.036728,3.515082,1,0.93

# Data del modelo

In [14]:
from pycaret.classification import save_model

In [15]:
MODELS_DIR = Path.cwd().resolve().parent / "modelos"
MODELS_DIR

WindowsPath('C:/Users/usuario/Desktop/za-proyecto-I/src/modelos')

In [16]:
MODELS_DIR.mkdir(exist_ok=True)

model_path = MODELS_DIR / "ramdon_fores_tuned_model"

save_model(gbc_tuned, model_path)

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['age', 'heart_rate', 'systolic_bp',
                                              'diastolic_bp', 'blood_sugar',
                                              'ckmb', 'troponin'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer',
                  Tra...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight=None, criterion='gini',
                                         max_depth=None, max_features='sqrt',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         monotonic_cst=None, n_estimators=100,
                                         n_jobs=-1, oob_score=False,
                                         random_state=42, verbose=0,
                                         warm_start=False))],
          verbose=False),
 'C:\\Users\\usuario\\Desktop\\za-proyecto-I\\src\\modelos\\ramdon_fores_tuned_model.pkl')