# Carga de datos

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df = pd.read_csv('../data/Medicaldataset.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1319 non-null   int64
 1   Gender                    1319 non-null   int64
 2   Heart rate                1319 non-null   int64
 3   Systolic blood pressure   1319 non-null   int64
 4   Diastolic blood pressure  1319 non-null   int64
 5   Blood sugar               1319 non-null   float64
 6   CK-MB                     1319 non-null   float64
 7   Troponin                  1319 non-null   float64
 8   Result                    1319 non-null   object
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB

In [3]:
df.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
0,64,1,66,160,83,160.0,1.80,0.012,negative
1,21,1,94,98,46,296.0,6.75,1.060,positive
2,55,1,64,160,77,270.0,1.99,0.003,negative
3,64,1,70,120,55,270.0,13.87,0.122,positive
4,55,1,64,112,65,300.0,1.08,0.003,negative

In [4]:
df.Result.unique()

array(['negative', 'positive'], dtype=object)

In [5]:
df.Result.value_counts()

Result
positive    810
negative    509
Name: count, dtype: int64

In [6]:
columnas_a_usar = [
    'Age',
    'Gender',
    'Heart rate',
    'Systolic blood pressure',
    'Diastolic blood pressure',
    'Blood sugar',
    'CK-MB',
    'Troponin',
    'Result'
]

In [7]:
df = df[columnas_a_usar]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1319 non-null   int64
 1   Gender                    1319 non-null   int64
 2   Heart rate                1319 non-null   int64
 3   Systolic blood pressure   1319 non-null   int64
 4   Diastolic blood pressure  1319 non-null   int64
 5   Blood sugar               1319 non-null   float64
 6   CK-MB                     1319 non-null   float64
 7   Troponin                  1319 non-null   float64
 8   Result                    1319 non-null   object
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB

# Ajuste de columnas

In [8]:
df.columns = df.columns.str.replace(' ','_').str.lower()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1319 non-null   int64
 1   gender                    1319 non-null   int64
 2   heart_rate                1319 non-null   int64
 3   systolic_blood_pressure   1319 non-null   int64
 4   diastolic_blood_pressure  1319 non-null   int64
 5   blood_sugar               1319 non-null   float64
 6   ck-mb                     1319 non-null   float64
 7   troponin                  1319 non-null   float64
 8   result                    1319 non-null   object
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB

In [9]:
df = df.rename(columns={'systolic_blood_pressure':'systolic_bp','diastolic_blood_pressure':'diastolic_bp'})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           1319 non-null   int64
 1   gender        1319 non-null   int64
 2   heart_rate    1319 non-null   int64
 3   systolic_bp   1319 non-null   int64
 4   diastolic_bp  1319 non-null   int64
 5   blood_sugar   1319 non-null   float64
 6   ck-mb         1319 non-null   float64
 7   troponin      1319 non-null   float64
 8   result        1319 non-null   object
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB

In [10]:
df = df.rename(columns={'ck-mb': 'ckmb'})

In [11]:
df['result'] = df['result'].replace({'negative': 0 ,'positive': 1 }).astype('int64')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           1319 non-null   int64
 1   gender        1319 non-null   int64
 2   heart_rate    1319 non-null   int64
 3   systolic_bp   1319 non-null   int64
 4   diastolic_bp  1319 non-null   int64
 5   blood_sugar   1319 non-null   float64
 6   ckmb          1319 non-null   float64
 7   troponin      1319 non-null   float64
 8   result        1319 non-null   int64
dtypes: float64(3), int64(6)
memory usage: 92.9 KB

In [13]:
df

,age,gender,heart_rate,systolic_bp,diastolic_bp,blood_sugar,ckmb,troponin,result
0,64,1,66,160,83,160.0,1.80,0.012,0
1,21,1,94,98,46,296.0,6.75,1.060,1
2,55,1,64,160,77,270.0,1.99,0.003,0
3,64,1,70,120,55,270.0,13.87,0.122,1
4,55,1,64,112,65,300.0,1.08,0.003,0
...,...,...,...,...,...,...,...,...,...
1314,44,1,94,122,67,204.0,1.63,0.006,0
1315,66,1,84,125,55,149.0,1.33,0.172,1
1316,45,1,85,168,104,96.0,1.24,4.250,1
1317,54,1,58,117,68,443.0,5.80,0.359,1
1318,51,1,94,157,79,134.0,50.89,1.770,1

# Creacion del archivo

In [14]:
ruta_datos = Path.cwd().resolve().parent / 'data'
ruta_datos

WindowsPath('C:/Users/usuario/Desktop/za-proyecto-I/data')

In [15]:
ruta_archivo = ruta_datos / "01_data_ataques_cardiacos.parquet"

ruta_datos.mkdir(parents=True, exist_ok=True)

df.to_parquet(ruta_archivo, index=False)