In [33]:
import numpy as np
import pandas as pd

from pathlib import Path
from pycaret.classification import setup, compare_models

In [34]:
DATA_DIR = Path.cwd().resolve().parent / "data"

df_data = pd.read_parquet(DATA_DIR / "02_data_ataques_cardiacos_transformados.parquet")

# Seleccion de columnas

In [35]:
df_data.columns

Index(['age', 'gender', 'heart_rate', 'systolic_bp', 'diastolic_bp',
       'blood_sugar', 'ckmb', 'troponin', 'result'],
      dtype='object')

In [36]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           1319 non-null   int64
 1   gender        1319 non-null   int64
 2   heart_rate    1319 non-null   float64
 3   systolic_bp   1319 non-null   float64
 4   diastolic_bp  1319 non-null   float64
 5   blood_sugar   1319 non-null   float64
 6   ckmb          1319 non-null   float64
 7   troponin      1319 non-null   float64
 8   result        1319 non-null   bool
dtypes: bool(1), float64(6), int64(2)
memory usage: 83.9 KB

In [37]:
target_col = 'result'

In [38]:
#Creacion del setup
models_setup = setup(
    data = df_data,
    target = target_col,
    session_id = 42,

    #Parametros para el pre-procesamiento
    numeric_features = ['age','heart_rate','systolic_bp','diastolic_bp','blood_sugar','ckmb','troponin'],
    categorical_features = ['gender'],

    #estrategias de imputacion
    numeric_imputation= 'mean',
    categorical_imputation = 'mode',
)

In [39]:
df_data['result'].value_counts()

result
True     810
False    509
Name: count, dtype: int64

In [40]:
best_model = compare_models(
    include = ['lr','rf','gbc','lightgbm','knn','xgboost'],
    sort = 'Accuracy',
    n_select = 3
)

Initiated  . . . . . . . . . . . . . . . . . .              22:47:18
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [41]:
from pycaret.classification import create_model, tune_model, predict_model

print("Creando el modelo Random Forest Classifier...")
gbc_model = create_model('rf')

print("\n")
print("------")
print("\n")

print("Realizando fine-tuning del modelo....")
gbc_tuned = tune_model(gbc_model)

print("\n")
print("------")
print("\n")

print("Resumen del modelo")
print(gbc_tuned)

print("\n")
print("------")
print("\n")

print("Predicciones en el conjunto/set de test")
internal_predictions = predict_model(gbc_tuned)

print("\n")
print("------")
print("\n")


print(internal_predictions.head())

Creando el modelo Random Forest Classifier...

------


Realizando fine-tuning del modelo....

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


------


Resumen del modelo
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=42, verbose=0,
                       warm_start=False)


------


Predicciones en el conjunto/set de test

------


      age  gender  heart_rate  systolic_bp  diastolic_bp  blood_sugar    ckmb  \
158    68       1        61.0        122.0          66.0         95.0   3.450
1174   37       0        83.0        102.0          68.0        104.0   1.350
78     50       1        64.0        110.0          58.0         90.0   0.994
346    60       1       134.0        111.0          69.0        163.0   3.080
699    65       1        87.0        115.0          78.0        119.0  17.320

      troponin  result  prediction_label  prediction_score
158      0.013   False                 0              0.89
1174     0.007   False                 0              0.96
78       0.864    True                 1              0.98
346      0.025    True                 1              0.96
699      1.390    True                 1              0.99

In [42]:
print(gbc_tuned.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

In [43]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           1319 non-null   int64
 1   gender        1319 non-null   int64
 2   heart_rate    1319 non-null   float64
 3   systolic_bp   1319 non-null   float64
 4   diastolic_bp  1319 non-null   float64
 5   blood_sugar   1319 non-null   float64
 6   ckmb          1319 non-null   float64
 7   troponin      1319 non-null   float64
 8   result        1319 non-null   bool
dtypes: bool(1), float64(6), int64(2)
memory usage: 83.9 KB

In [44]:
np.random.seed(42)

n_samples = 80

df_data_test = pd.DataFrame({
    'age':np.random.uniform(14,103, size=n_samples),
    'gender':np.random.choice([0,1], size=n_samples),
    'heart_rate':np.random.uniform(20,1111, size=n_samples),
    'systolic_bp':np.random.uniform(42,223, size=n_samples),
    'diastolic_bp':np.random.uniform(38,154, size=n_samples),
    'blood_sugar':np.random.uniform(35,541, size=n_samples),
    'ckmb':np.random.uniform(0.3,300, size=n_samples),
    'troponin':np.random.uniform(0.00,10.3, size=n_samples)
})

df_data_test.head()

,age,gender,heart_rate,systolic_bp,diastolic_bp,blood_sugar,ckmb,troponin
0,47.334071,0,900.917209,158.207728,141.240620,231.413983,25.725863,6.119546
1,98.613573,0,997.635608,57.229334,77.207438,360.503839,295.995882,3.923176
2,79.147461,1,366.941791,71.254797,81.567623,266.875963,112.468957,9.990118
3,67.280605,1,140.066650,204.638308,48.901905,311.082095,111.381451,8.673825
4,27.885659,1,268.677262,151.763660,105.080496,511.381193,243.896030,8.634786

In [45]:
synthetic_predictions = predict_model(gbc_model, data=df_data_test)

synthetic_predictions.head()

,age,gender,heart_rate,systolic_bp,diastolic_bp,blood_sugar,ckmb,troponin,prediction_label,prediction_score
0,47.334072,0,900.917236,158.207733,141.240616,231.413986,25.725863,6.119546,1,0.96
1,98.613571,0,997.635620,57.229332,77.207436,360.503845,295.995880,3.923176,1,0.94
2,79.147461,1,366.941803,71.254799,81.567619,266.875977,112.468956,9.990118,1,0.94
3,67.280602,1,140.066650,204.638306,48.901905,311.082092,111.381454,8.673825,1,0.95
4,27.885658,1,268.677277,151.763657,105.080498,511.381195,243.896027,8.634786,1,0.95

# Data del modelo

In [46]:
from pycaret.classification import save_model

In [47]:
MODELS_DIR = Path.cwd().resolve().parent / "modelos"
MODELS_DIR

WindowsPath('C:/Users/usuario/Desktop/za-proyecto-I/src/modelos')

In [48]:
MODELS_DIR.mkdir(exist_ok=True)

model_path = MODELS_DIR / "random_forest_tuned_model"

save_model(gbc_tuned, model_path)

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['age', 'heart_rate', 'systolic_bp',
                                              'diastolic_bp', 'blood_sugar',
                                              'ckmb', 'troponin'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer',
                  Tra...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight=None, criterion='gini',
                                         max_depth=None, max_features='sqrt',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         monotonic_cst=None, n_estimators=100,
                                         n_jobs=-1, oob_score=False,
                                         random_state=42, verbose=0,
                                         warm_start=False))],
          verbose=False),
 'C:\\Users\\usuario\\Desktop\\za-proyecto-I\\src\\modelos\\random_forest_tuned_model.pkl')